In [2]:
import pandas as pd
data=pd.read_excel(r"Data_before_cleaning.xlsx")
data=data.sort_values(by='ORDERNUMBER')
data

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1267,10100,22,86.51,4,1903.22,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Small
578,10100,30,100.00,3,5151.00,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
680,10100,50,67.80,2,3390.00,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
2024,10100,49,34.47,1,1689.03,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Small
728,10101,25,100.00,4,3782.00,2003-01-09,Shipped,1,1,2003,...,Lyonerstr. 34,NaN,Frankfurt,NaN,60528,Germany,EMEA,Keitel,Roland,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,10425,38,100.00,13,4325.16,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
2405,10425,18,100.00,2,1895.94,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
1465,10425,55,46.82,1,2575.10,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
679,10425,28,100.00,3,5318.04,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
727,10425,38,99.41,7,3777.58,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium

In [3]:
def strf(s):
    g=''
    for i in s:
        if  i.isdigit():
            g+=i
    return g
data['PHONE']=data['PHONE'].apply(lambda x : strf(str(x)))
data

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1267,10100,22,86.51,4,1903.22,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Small
578,10100,30,100.00,3,5151.00,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
680,10100,50,67.80,2,3390.00,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
2024,10100,49,34.47,1,1689.03,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Small
728,10101,25,100.00,4,3782.00,2003-01-09,Shipped,1,1,2003,...,Lyonerstr. 34,NaN,Frankfurt,NaN,60528,Germany,EMEA,Keitel,Roland,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,10425,38,100.00,13,4325.16,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
2405,10425,18,100.00,2,1895.94,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
1465,10425,55,46.82,1,2575.10,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
679,10425,28,100.00,3,5318.04,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
727,10425,38,99.41,7,3777.58,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium

In [4]:
# nullvalues =data['ADDRESSLINE2'].isnull().count()-data['ADDRESSLINE2'].count()# 2521
# ad2=data['ADDRESSLINE2'].drop_duplicates().count()# only have 9 address2
#drop address2
# data.drop('ADDRESSLINE2')
# data.drop('ADDRESSLINE2',axis='columns')
data #after remove address2

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1267,10100,22,86.51,4,1903.22,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Small
578,10100,30,100.00,3,5151.00,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
680,10100,50,67.80,2,3390.00,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
2024,10100,49,34.47,1,1689.03,2003-01-06,Shipped,1,1,2003,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Small
728,10101,25,100.00,4,3782.00,2003-01-09,Shipped,1,1,2003,...,Lyonerstr. 34,NaN,Frankfurt,NaN,60528,Germany,EMEA,Keitel,Roland,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,10425,38,100.00,13,4325.16,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
2405,10425,18,100.00,2,1895.94,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
1465,10425,55,46.82,1,2575.10,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Small
679,10425,28,100.00,3,5318.04,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium
727,10425,38,99.41,7,3777.58,2005-05-31,In Process,2,5,2005,...,"67, rue des Cinquante Otages",NaN,Nantes,NaN,44000,France,EMEA,Labrune,Janine,Medium

Make a Column of State and Remove it from Data

In [5]:
print(data['STATE'].isnull().count())
print(data['STATE'].count())# null values
print(data['STATE'].drop_duplicates())

2823
1337
1267               NH
728               NaN
501                NY
448                PA
476                CA
805          Victoria
1394               NV
937                MA
2745               CT
2075              NSW
2254       Queensland
453            Quebec
2623               BC
1573            Osaka
1076    Isle of Wight
2468               NJ
225             Tokyo
Name: STATE, dtype: object

In [6]:
new_column_of_State = data[['ORDERNUMBER','STATE']].drop_duplicates()
column_State_count=data['STATE'].value_counts()
column_State_count
data=data.drop('STATE',axis='columns') #it is removed

In [7]:
data

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1267,10100,22,86.51,4,1903.22,2003-01-06,Shipped,1,1,2003,...,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,NaN,Young,Valarie,Small
578,10100,30,100.00,3,5151.00,2003-01-06,Shipped,1,1,2003,...,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,NaN,Young,Valarie,Medium
680,10100,50,67.80,2,3390.00,2003-01-06,Shipped,1,1,2003,...,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,NaN,Young,Valarie,Medium
2024,10100,49,34.47,1,1689.03,2003-01-06,Shipped,1,1,2003,...,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,NaN,Young,Valarie,Small
728,10101,25,100.00,4,3782.00,2003-01-09,Shipped,1,1,2003,...,496966902555,Lyonerstr. 34,NaN,Frankfurt,60528,Germany,EMEA,Keitel,Roland,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,10425,38,100.00,13,4325.16,2005-05-31,In Process,2,5,2005,...,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,EMEA,Labrune,Janine,Medium
2405,10425,18,100.00,2,1895.94,2005-05-31,In Process,2,5,2005,...,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,EMEA,Labrune,Janine,Small
1465,10425,55,46.82,1,2575.10,2005-05-31,In Process,2,5,2005,...,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,EMEA,Labrune,Janine,Small
679,10425,28,100.00,3,5318.04,2005-05-31,In Process,2,5,2005,...,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,EMEA,Labrune,Janine,Medium
727,10425,38,99.41,7,3777.58,2005-05-31,In Process,2,5,2005,...,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,EMEA,Labrune,Janine,Medium

Make a Column of TERRITORY and Remove it from Data

In [8]:
print(data['TERRITORY'].isnull().count())
print(data['TERRITORY'].count())# null values
print(data['TERRITORY'].drop_duplicates())

2823
1749
1267      NaN
728      EMEA
2432    Japan
805      APAC
Name: TERRITORY, dtype: object

In [9]:
new_column_of_TERRITORY= data[['ORDERNUMBER','TERRITORY']].drop_duplicates()
column_TERRITORY_count=data['TERRITORY'].value_counts()
column_TERRITORY_count
data=data.drop('TERRITORY',axis='columns')

In [10]:
data

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CUSTOMERNAME,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1267,10100,22,86.51,4,1903.22,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Small
578,10100,30,100.00,3,5151.00,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Medium
680,10100,50,67.80,2,3390.00,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Medium
2024,10100,49,34.47,1,1689.03,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Small
728,10101,25,100.00,4,3782.00,2003-01-09,Shipped,1,1,2003,...,"Blauer See Auto, Co.",496966902555,Lyonerstr. 34,NaN,Frankfurt,60528,Germany,Keitel,Roland,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,10425,38,100.00,13,4325.16,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium
2405,10425,18,100.00,2,1895.94,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Small
1465,10425,55,46.82,1,2575.10,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Small
679,10425,28,100.00,3,5318.04,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium
727,10425,38,99.41,7,3777.58,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium

In [11]:
data.isnull().count()-data.count() #POSTALCODE  is 76

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
POSTALCODE            76
COUNTRY                0
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [12]:
data['POSTALCODE']=data['POSTALCODE'].fillna('UnKnow')

In [13]:
data

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CUSTOMERNAME,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1267,10100,22,86.51,4,1903.22,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Small
578,10100,30,100.00,3,5151.00,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Medium
680,10100,50,67.80,2,3390.00,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Medium
2024,10100,49,34.47,1,1689.03,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Small
728,10101,25,100.00,4,3782.00,2003-01-09,Shipped,1,1,2003,...,"Blauer See Auto, Co.",496966902555,Lyonerstr. 34,NaN,Frankfurt,60528,Germany,Keitel,Roland,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,10425,38,100.00,13,4325.16,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium
2405,10425,18,100.00,2,1895.94,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Small
1465,10425,55,46.82,1,2575.10,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Small
679,10425,28,100.00,3,5318.04,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium
727,10425,38,99.41,7,3777.58,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium

In [14]:
data.isnull().count()-data.count() #no NULL

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
POSTALCODE             0
COUNTRY                0
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [15]:
data

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CUSTOMERNAME,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
1267,10100,22,86.51,4,1903.22,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Small
578,10100,30,100.00,3,5151.00,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Medium
680,10100,50,67.80,2,3390.00,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Medium
2024,10100,49,34.47,1,1689.03,2003-01-06,Shipped,1,1,2003,...,Online Diecast Creations Co.,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Small
728,10101,25,100.00,4,3782.00,2003-01-09,Shipped,1,1,2003,...,"Blauer See Auto, Co.",496966902555,Lyonerstr. 34,NaN,Frankfurt,60528,Germany,Keitel,Roland,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,10425,38,100.00,13,4325.16,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium
2405,10425,18,100.00,2,1895.94,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Small
1465,10425,55,46.82,1,2575.10,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Small
679,10425,28,100.00,3,5318.04,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium
727,10425,38,99.41,7,3777.58,2005-05-31,In Process,2,5,2005,...,La Rochelle Gifts,40678555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium

In [17]:
data.to_excel("Data_After_Cleaning.xlsx",index=False)